### ISSUE TITLE
[Feature] Add ability to customize webhook https and capi port

### ISSUE THREAD

**Issue by fauzanelka** [rancher/webhook#211]
So I have an EKS cluster with Calico CNI installed.
When I installed rancher into the EKS cluster via helm chart, I ran into these problems.

1. I want to use hostNetwork for rancher-webhook but I don't know how to specify helm values for rancher-webhook. It seems rancher automatically install the chart. So I just edit it directly via the deployment yaml.
3. I just did briefly check the source code but it seems didn't have the ability to specify custom webhook https and capi ports. This is needed for hostNetwork because when ports 9443 and 8777 are already used by another deployment (e.g. aws-load-balancer-controller). The rancher webhook pod won't start (stuck at pending). It's good that I can change the aws-load-balancer-controller webhook port via webhookBindPort so the problem was solved.

**Comment by bryanasdev000** [comment]
I need to test, but in theory, rancher chart expose a global var, and rancher-webhook can use it.

- https://github.com/rancher/charts/blob/dev-v2.7/charts/rancher-webhook/1.0.8%2Bup0.2.9/values.yaml#L6
- https://artifacthub.io/packages/helm/rancher-stable/rancher?modal=values

Will try it.

**Comment by KevinJoiner** [comment]
We are looking at this now and I will update this issue when there is some more movement.

**Comment by anupama2501** [comment]
@cpinjani to validate the EKS related changes

**Comment by anupama2501** [comment]
Closing the issue as the validations run as part of the issue https://github.com/rancher/rancher/issues/41142#issuecomment-1667674189 look good.
