### ISSUE TITLE
Startup probe failed: HTTP probe failed with statuscode: 500

### ISSUE THREAD

**Issue by mak241265** [rancher/webhook#265]
Hello everyone
Recently i installed kubernetes(v.1.26.4) 9nodes with RKE version: v1.4.6. Then we decided to use rancher for our k8s platform management.we brought up rancher v2.7.5 on signle docker container and imported our existing cluster on it.everything seems perfect without problem...but after a while we were noticed we can not create any resources with kubectl due to rancher webhook...we checked the webhook pod in cattle-system by kubectl describe :
-Warning  Unhealthy  18m (x3 over 18m)  kubelet            Startup probe failed: HTTP probe failed with statuscode: 500
the kubernetes cni is calico installed by operator..there is no ufw enabled on nodes and all nodes and rancher servers are in same VLAN without any restriction.

**Comment by carlosmds** [comment]
Same issue here on EKS v1.27, rancher is running OK, but webhook is unhealthy with message  "Startup probe failed: HTTP probe failed with statuscode: 500". I wish there was a way to debug this.

**Comment by carlosmds** [comment]
Logs don't give much info about it.
```
time="2023-08-01T19:26:26Z" level=info msg="Rancher-webhook version v0.3.5 (2e89c65) is starting"
time="2023-08-01T19:26:26Z" level=info msg="Active TLS secret cattle-system/cattle-webhook-tls (ver=345209625) (count 1): map[listener.cattle.io/cn-rancher-webhook.cattle-system.svc:rancher-webhook.cattle-system.svc listener.cattle.io/fingerprint:SHA1=F0AD9B71BCDDEB8B3BC9E00015BE84BC80D7B558]"
time="2023-08-01T19:26:26Z" level=info msg="Listening on :9443"
time="2023-08-01T19:26:27Z" level=info msg="Starting apiextensions.k8s.io/v1, Kind=CustomResourceDefinition controller"
time="2023-08-01T19:26:27Z" level=info msg="Starting rbac.authorization.k8s.io/v1, Kind=Role controller"
time="2023-08-01T19:26:27Z" level=info msg="Starting management.cattle.io/v3, Kind=PodSecurityAdmissionConfigurationTemplate controller"
time="2023-08-01T19:26:27Z" level=info msg="Starting management.cattle.io/v3, Kind=ProjectRoleTemplateBinding controller"
time="2023-08-01T19:26:27Z" level=info msg="Starting rbac.authorization.k8s.io/v1, Kind=RoleBinding controller"
time="2023-08-01T19:26:27Z" level=info msg="Starting /v1, Kind=Secret controller"
time="2023-08-01T19:26:27Z" level=info msg="Sleeping for 15 seconds then applying webhook config"
time="2023-08-01T19:26:27Z" level=info msg="Starting management.cattle.io/v3, Kind=GlobalRole controller"
time="2023-08-01T19:26:27Z" level=info msg="Starting rbac.authorization.k8s.io/v1, Kind=ClusterRoleBinding controller"
time="2023-08-01T19:26:27Z" level=info msg="Starting management.cattle.io/v3, Kind=RoleTemplate controller"
time="2023-08-01T19:26:27Z" level=info msg="Starting provisioning.cattle.io/v1, Kind=Cluster controller"
time="2023-08-01T19:26:27Z" level=info msg="Starting rbac.authorization.k8s.io/v1, Kind=ClusterRole controller"
time="2023-08-01T19:26:27Z" level=info msg="Starting management.cattle.io/v3, Kind=Cluster controller"
time="2023-08-01T19:26:27Z" level=info msg="Starting apiregistration.k8s.io/v1, Kind=APIService controller"
time="2023-08-01T19:26:27Z" level=info msg="Starting management.cattle.io/v3, Kind=ClusterRoleTemplateBinding controller"
time="2023-08-01T19:26:27Z" level=info msg="Updating TLS secret for cattle-system/cattle-webhook-tls (count: 1): map[listener.cattle.io/cn-rancher-webhook.cattle-system.svc:rancher-webhook.cattle-system.svc listener.cattle.io/fingerprint:SHA1=F0AD9B71BCDDEB8B3BC9E00015BE84BC80D7B558]"
time="2023-08-01T19:26:27Z" level=info msg="Active TLS secret cattle-system/cattle-webhook-tls (ver=351408238) (count 1): map[listener.cattle.io/cn-rancher-webhook.cattle-system.svc:rancher-webhook.cattle-system.svc listener.cattle.io/fingerprint:SHA1=F0AD9B71BCDDEB8B3BC9E00015BE84BC80D7B558]"
time="2023-08-01T19:26:27Z" level=info msg="Updating TLS secret for cattle-system/cattle-webhook-tls (count: 1): map[listener.cattle.io/cn-rancher-webhook.cattle-system.svc:rancher-webhook.cattle-system.svc listener.cattle.io/fingerprint:SHA1=F0AD9B71BCDDEB8B3BC9E00015BE84BC80D7B558]"
```

**Comment by sepdevops** [comment]
@carlosmds after a long time researching i found there is something wrong with my CNI configuration..my CNI overlay network was set to VXLAN and i read if the mtu of network interfaces is low you'd face this problem...i switched to IPIP and everything solved...please consider i had some other problems as well and everything was solved with this change..

**Comment by mak241265** [comment]
@carlosmds after a long time researching i found there is something wrong with my CNI configuration..my CNI overlay network was set to VXLAN and i read if the mtu of network interfaces is low you'd face this problem...i switched to IPIP and everything solved...please consider i had some other problems as well and everything was solved with this change..

**Comment by KevinJoiner** [comment]
@carlosmds Yeah, we should update the logs to help with this use case for now 
you can check the response message of the startup probe `/healthz` to see why it hasn't started.

**Comment by robcharlwood** [comment]
@mak241265 - please could you provide a little more information as to how you solved this?
We are seeing this issue in our GKE Rancher install and in our downstream clusters (some cloud, some on prem).

Thanks!

**Comment by mak241265** [comment]
> @mak241265 - please could you provide a little more information as to how you solved this? We are seeing this issue in our GKE Rancher install and in our downstream clusters (some cloud, some on prem).
> 
> Thanks!

@robcharlwood actually i just changed my calico CNI to IPinIP mode...to be honest i think i had some network problems as well.in addition i found a link which mentions when you network MTU is not sufficient you might face these kind of problems.
